#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build openedx container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2

      CUSTOM_THEME_REPOSITORY: gcsi-openedx-theme
      CUSTOM_THEME_REPOSITORY_ORGANIZATION: GCSI
      CUSTOM_THEME_REPOSITORY_REF: main

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #------------------------------------------------------------------------
      # install and configure tutor
      #  
      #------------------------------------------------------------------------
      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@v1.0.8
        with: 
          kubectl-version: "1.25"
          tutor-version: "14.2.3"
          tutor-mfe-version: "14.0.2"

      # - name: Load additional environment specific settings
      #   shell: bash
      #   run: |-
      #     tutor config save --set OPENEDX_COMMON_VERSION=open-release/nutmeg.3

      #------------------------------------------------------------------------
      # Add a custom theme here.
      #------------------------------------------------------------------------
      - name: Add a custom theme
        uses: openedx-actions/tutor-plugin-build-openedx-add-theme@v1.0.0
        with:
          repository: ${{ env.CUSTOM_THEME_REPOSITORY }}
          repository-organization: ${{ env.CUSTOM_THEME_REPOSITORY_ORGANIZATION }}
          repository-ref: ${{ env.CUSTOM_THEME_REPOSITORY_REF }}
          repository-token: ${{ secrets.PAT }}

      #------------------------------------------------------------------------
      # Add any Python requirements here.
      # These include:
      # - generic Python PyPi packages
      # - Xblocks
      # - Open edX Plugin(s)
      # - your own custom repos
      #
      # note that `repository-token` is optional and is only needed for
      # private repositories
      #------------------------------------------------------------------------
      - name: Add an GCSI custom openedx plugin
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v1.0.5
        with:
          repository: gcsi-digital-learning-openedx
          repository-organization: GCSI
          repository-ref: dob/cache-invalidation
          repository-token: ${{ secrets.PAT }}

      - name: Add Xblock - xblock-in-video-quiz
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v1.0.5
        with:
          repository: xblock-in-video-quiz
          repository-organization: Stanford-Online
          repository-ref: master
          repository-token: ${{ secrets.PAT }}

      - name: Add Xblock - xblock-activetable
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v1.0.5
        with:
          repository: xblock-activetable
          repository-organization: open-craft
          repository-ref: master
          repository-token: ${{ secrets.PAT }}

      - name: Add xblock-free-text-response
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v1.0.5
        with:
          repository: xblock-free-text-response
          repository-organization: openedx
          repository-ref: master
          repository-token: ${{ secrets.PAT }}

      #------------------------------------------------------------------------
      # Build and upload the Docker container
      #------------------------------------------------------------------------
      - name: Build openedx
        uses: openedx-actions/tutor-plugin-build-openedx@v1.0.2